{
 "title": "Cold Chain Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "longitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cold_chain_data\")\n  |> filter(fn: (r) => r._field == \"longitude\")\n"
    }
   ]
  },
  {
   "title": "lattitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cold_chain_data\")\n  |> filter(fn: (r) => r._field == \"latitude\")\n"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cold_chain_data\")\n  |> filter(fn: (r) => r._field == \"light\")\n"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cold_chain_data\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n"
    }
   ]
  },
  {
   "title": "Temperature Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cold_chain_data\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n"
    }
   ]
  }
 ]
}